
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 6.6
 PARAMETER PROC_INSTANCE = design_1_i_microblaze_0
 PARAMETER profile_timer = design_1_i_axi_timer_0
 PARAMETER sleep_timer = design_1_i_axi_timer_0
 PARAMETER stdin = design_1_i_axi_uartlite_0
 PARAMETER stdout = design_1_i_axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.6
 PARAMETER HW_INSTANCE = design_1_i_microblaze_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = mydecisionslave
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = design_1_i_MyDecisionMakingBlock_mydecisionslave_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mydecisionslave_2
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = design_1_i_MyDecisionMakingBlock_mydecisionslave_2_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emaclite
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = design_1_i_axi_ethernetlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = design_1_i_axi_timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = design_1_i_axi_timer_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = design_1_i_axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.7
 PARAMETER HW_INSTANCE = design_1_i_microblaze_0_axi_intc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = design_1_i_microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = design_1_i_microblaze_0_local_memory_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mig_7series
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = design_1_i_mig_7series_0
END


BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = lwip211
 PARAMETER LIBRARY_VER = 1.1
 PARAMETER PROC_INSTANCE = design_1_i_microblaze_0
 PARAMETER phy_link_speed = CONFIG_LINKSPEED100
END


